# This compose file is for demonstration only, do not use in prod.
services:
  app:
    image: polynex/logto:${VERSION:-1.41.1}
    entrypoint: [ "sh", "-c", "npm run cli db seed -- --swe && npm start" ]
    expose:
      - 3001
      - 3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=${DB_URL:-postgres://postgres:p0stgr3s@postgres:5432/logto}
      - REDIS_URL=${REDIS_URL:-redis://:p0stgr3s@postgres:6379}
      # Optional default grace period, in seconds, for OIDC private key rotation when the API
      # request omits `rotationGracePeriod`.
      - PRIVATE_KEY_ROTATION_GRACE_PERIOD
      # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
      # Or, you can leverage it for local testing.
      - ENDPOINT
      - ADMIN_ENDPOINT

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/logto.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
