# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name auth.qutewear.com admin.qutewear.com;
    return 301 https://$host$request_uri;
}

# User / Auth Core Service (3001)
server {
    listen 443 ssl;
    server_name auth.qutewear.com;

    ssl_certificate /etc/nginx/ssl/logto.crt;
    ssl_certificate_key /etc/nginx/ssl/logto.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 10M;

    location / {
        proxy_pass http://app:3001;
        proxy_http_version 1.1;
        
        # Websocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Proxy headers
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Admin Console / API (3002)
server {
    listen 443 ssl;
    server_name admin.qutewear.com;

    ssl_certificate /etc/nginx/ssl/logto.crt;
    ssl_certificate_key /etc/nginx/ssl/logto.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 10M;

    location / {
        proxy_pass http://app:3002;
        proxy_http_version 1.1;

        # Websocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Proxy headers
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
